apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-streamlitv1
  labels:
    app: py-streamlitv1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-streamlitv1
  template:
    metadata:
      labels:
        app: py-streamlitv1
    spec:
      containers:
        - name: py-streamlitv1
          image: hjyuni/my-repo:streamlitv1
          ports:
            - containerPort: 8501
              name: py-streamlitv1
      imagePullSecrets:
        - name: dockersecret