-- CHECK ROLE LIST
\du

-- CREATE ROLE
CREATE user HJY WITH PASSWORD 'abcd';
\du

-- ALTER ROLE
ALTER user HJY WITH SUPERUSER;
ALTER user HJY WITH CREATEDB;
ALTER user HJY WITH CREATEROLE;
ALTER user HJY WITH REPLICATION;
ALTER user HJY WITH BYPASSRLS;
\du

-- GRANT 권한 ON 테이블명 TO 사용자명
GRANT SELECT ON num_subs TO HJY;
-- REVOKE 권한 ON 테이블명 FROM 사용자명
REVOKE SELECT ON num_subs FROM HJY;

-- DROP USER
DROP user HJY;